spring.application.name=b2b

spring.datasource.url=jdbc:postgresql://localhost:5433/b2b
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.default_schema=b2b
spring.docker.compose.enabled=false

springdoc.override-with-generic-response=false
